Feat/show loading card
clober-dex/coupon.finance pull request #298
Opened 2023-11-15 10:33 UTC by graykode

2023-11-15 12:35 UTC, onemonster requested changes
Instead of using an arbitrary 10 seconds to filter out pending deposits, why don't we use the block number from the subgraph, and compare the block number of the subgraph with the block number of the transaction that created the deposit. If the block number is bigger than the subgraph we consider it pending.

2023-11-16 05:04 UTC, Dorvin approved these changes

2023-11-16 05:04 UTC, Dorvin commented on contexts/deposit-context.tsx
> +        previousConformationPositions.current = []
p2; need to remove this line

2023-11-16 05:36 UTC, onemonster commented on contexts/borrow-context.tsx
> +        conformationPositions.length !==
Using length to check equality could cause unexpected bugs.

2023-11-16 07:15 UTC, onemonster commented on contexts/borrow-context.tsx
> +      const conformationPositions = await fetchLoanPositions(
`confirmedPositions`

2023-11-16 07:15 UTC, Dorvin approved these changes

2023-11-16 07:21 UTC, onemonster approved these changes

2023-11-16 07:32 UTC, merged