feat: breaking changes in slider component
clober-dex/coupon.finance pull request #303
Opened 2023-11-16 01:10 UTC by 0xgabii

2023-11-16 06:58 UTC, graykode requested changes
.

2023-11-16 09:15 UTC, 0xgabii reviewed
.

2023-11-27 07:36 UTC, graykode commented on pages/deposit/[symbol].tsx
> +                      epochs + 1,
```suggestion
                      epochs,
```
@Dorvin Let's move +1 logic to deposit context

2023-11-27 07:39 UTC, graykode commented on pages/deposit/[symbol].tsx
> +                      epochs + 1,
@Dorvin Include a TODO comment for when the contract interface is changed.

2023-11-27 07:45 UTC, graykode commented on containers/form/borrow-form-container.tsx
> +            epochs + 1,
p2; same with deposit @Dorvin

2023-11-27 07:53 UTC, graykode commented on containers/modal/edit-expiry-modal-container.tsx
> +          .slice(epochs + 1, expiryEpochIndex + 1)
p1; @Dorvin 
```suggestion
          .slice(epochs, expiryEpochIndex + 1)
```

2023-11-27 07:53 UTC, graykode commented on containers/modal/edit-expiry-modal-container.tsx
> +          .slice(epochs + 1, expiryEpochIndex + 1)
p1; @Dorvin 
```suggestion
          .slice(epochs, expiryEpochIndex + 1)
```

2023-11-27 07:57 UTC, graykode commented
@Dorvin I found bug when calculate expected refund amount: https://github.com/clober-dex/coupon.finance/pull/303/commits/5b75db9fc3e50f81ff47e5385ee9ce407f5796e9

2023-11-27 08:20 UTC, Dorvin approved these changes

2023-11-27 08:20 UTC, merged